# Generated by Django 4.0.3 on 2022-03-12 20:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ebackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer',
            new_name='BuyerProfile',
        ),
        migrations.RenameModel(
            old_name='Vendor',
            new_name='VendorProfile',
        ),
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={'permissions': [('can_view_products', 'can view products')]},
        ),
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'permissions': [('can_edit_products', 'can edit products'), ('can_view_products', 'can view products')]},
        ),
    ]
