# Generated by Django 4.0.3 on 2022-04-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ebackend', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('bought_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ebackend.buyerprofile')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ebackend.vendorprofile')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Ebackend.product')),
            ],
        ),
    ]
