# Generated by Django 4.0.3 on 2022-03-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebackend', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='address',
            field=models.TextField(blank=True, default='Some address!', max_length=2000000, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(blank=True, default='Some address!', max_length=2000000, null=True),
        ),
    ]
