# Generated by Django 4.0.3 on 2022-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebackend', '0005_buyerprofile_address_vendorprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='phone',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
