# Generated by Django 4.0.3 on 2022-04-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebackend', '0007_alter_buyerprofile_phone_alter_vendorprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='phone',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
